language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install .
  - pip install coverage
  - pip install coveralls
  - pip freeze
script:
  - make tests
after_success:
  - coveralls
